### ISSUE TITLE
Nonaktifkan redirect https di beberapa endpoint b.o.i

### ISSUE THREAD

**Issue by artemtech** [BlankOn/Verbeek#112]
Berikut layanan yang semestinya tidak redirect ke https:
- [x] `arsip-dev.boi`

**Comment by herpiko** [comment]
Saya menambahkan ini di envoy.yaml

```
  - name: listener_0
    address:
      socket_address: { address: 0.0.0.0, port_value: 80 }
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          codec_type: AUTO
          route_config:
            name: local_route
            virtual_hosts:
            - name: irgsh_repo_service
              domains: ["arsip-dev.blankonlinux.or.id"]
              routes:
              - match: { prefix: "/" }
                route: { cluster: irgsh-repo, timeout: 0s}
          http_filters:
          - name: envoy.filters.http.router
  - name: listener_1
    address:
```

@artemtech Mohon dicek kembali. Tiketnya bisa ditutup bila sudah memenuhi ekspektasi.
